Create appointment step one
corona-school/user-app pull request #114
Opened 2023-01-27 12:14 UTC by LomyW

Uses `subcourses` and `lectures` at the moment. Will be adjusted, when BE is ready :)

2023-01-31 09:26 UTC, timidak requested changes
Few changes to be made 🙂

2023-01-31 09:26 UTC, timidak commented on src/pages/create-appointment/AppointmentAssignment.tsx
> +        });
I guess this should do the job honestly ☺️ 
```suggestion
        const sortedCourses: LFSubCourse[] = publishedSubcourses.sort((a: LFSubCourse, b: LFSubCourse) => {
            const aInMillis = DateTime.fromISO(a.firstLecture.start).toMillis();
            const bInMillis = DateTime.fromISO(b.firstLecture.start).toMillis();
            return aInMillis - bInMillis;
        });
```

2023-01-31 09:26 UTC, timidak commented on src/pages/create-appointment/AppointmentAssignment.tsx
> +        }
This should be done in a database query in the backend because of performance reasons

2023-01-31 09:26 UTC, timidak commented on src/pages/create-appointment/AppointmentAssignment.tsx
> +                        title: 'Einzel',
add to i18n

2023-01-31 09:26 UTC, timidak commented on src/pages/create-appointment/AppointmentAssignment.tsx
> +                                                key={`match ${index}`}
use the match id? Using array indexes can lead to issues in React.

2023-01-31 09:26 UTC, timidak commented on src/pages/create-appointment/AppointmentAssignment.tsx
> +                        title: 'Gruppe',
add to i18n

2023-01-31 09:26 UTC, timidak commented on src/pages/create-appointment/AppointmentAssignment.tsx
> +                                                key={`course-${index}`}
use course id? or something unique for this tile

2023-01-31 09:26 UTC, timidak commented on src/widgets/appointment/AssignmentTile.tsx
> +                                        ? `${DateTime.fromISO(props.startDate).setLocale('de').toFormat('Ab DD • t')} Uhr`
This should be made with i18n and we should never force a local. Because bringing in the next language will break spots like this in the code

2023-01-31 12:15 UTC, LomyW commented on src/pages/Appointments.tsx
> +                <FloatingActionButton handlePress={() => navigate('/create-appointment')} place={fabPlace} />
yes, button is also renamed in another PR.

2023-02-01 15:31 UTC, jeffersondarcy commented on src/NavigatorLazy.tsx
> +                        <SwitchUserType pupilComponent={<Dashboard />} studentComponent={<CreateAppointment />} />
should the route be present for pupils or should they may be be redirected or get a 404?

2023-02-01 15:33 UTC, jeffersondarcy commented on src/pages/Appointments.tsx
> +                <FloatingActionButton handlePress={() => navigate('/create-appointment')} place={buttonPlace} />
is this button hidden for pupils?

2023-02-01 15:35 UTC, jeffersondarcy commented on src/pages/CreateAppointment.tsx
> +                    {currentIndex === 0 && <AppointmentAssignment next={onNext} back={onBack} />}
should this only be displayed when currentIndex === 0?

2023-02-01 15:39 UTC, jeffersondarcy commented on src/pages/create-appointment/AppointmentAssignment.tsx
> +                                        if (!first)
the code blocks with AssignmentTile look very similar, can you avoid duplication

2023-02-01 15:52 UTC, LomyW commented on src/NavigatorLazy.tsx
> +                        <SwitchUserType pupilComponent={<Dashboard />} studentComponent={<CreateAppointment />} />
I think redirect, what are an advantage of an error 404?

2023-02-01 15:52 UTC, LomyW commented on src/pages/Appointments.tsx
> +                <FloatingActionButton handlePress={() => navigate('/create-appointment')} place={buttonPlace} />
yes, is also renamed in the another PR.

2023-02-01 15:53 UTC, LomyW commented on src/pages/CreateAppointment.tsx
> +                    {currentIndex === 0 && <AppointmentAssignment next={onNext} back={onBack} />}
yes, do you see another case when to display?

2023-02-01 15:54 UTC, jeffersondarcy commented on src/pages/create-appointment/AppointmentAssignment.tsx
> +const AppointmentAssignment: React.FC<AssignmentProps> = ({ next, back }) => {
not sure about naming "assignment". is this the logic for step 1? could we name it something like "StepEditAppointmentConfiguration" but better :)?

2023-02-01 15:57 UTC, jeffersondarcy commented on src/widgets/appointment/AssignmentTile.tsx
> +const AssignmentTile: React.FC<TileProps> = (props) => {
What is "AssignmentTile"? should it be called "...Form" or something more clear?

2023-02-01 15:59 UTC, jeffersondarcy commented on src/widgets/appointment/AssignmentTile.tsx
> +    return (
would it make sense to create separate components for every field?

2023-02-01 16:01 UTC, jeffersondarcy requested changes
some naming and structure suggestions

2023-02-01 16:03 UTC, LomyW commented on src/pages/create-appointment/AppointmentAssignment.tsx
> +                tabs={[
I would not make separate components. I have removed one Tile in tab group, so it looks better (see changes).

2023-02-01 16:04 UTC, LomyW commented on src/widgets/appointment/AssignmentTile.tsx
> +const AssignmentTile: React.FC<TileProps> = (props) => {
Form is relevant in step 3, when we create the new appointment. So I didn't rename it to form here.

2023-02-02 12:15 UTC, timidak approved these changes
Good job 👍🏻

2023-02-02 13:25 UTC, merged