Create appointment step 2
corona-school/user-app pull request #120
Opened 2023-01-30 12:43 UTC by LomyW

2023-02-03 12:30 UTC, LomyW commented on src/widgets/appointment/AppointmentList.tsx
> +    isStatic: boolean;
open for name suggestions

2023-02-03 12:31 UTC, LomyW commented on src/pages/create-appointment/AppointmentsView.tsx
> +// query myappointments {
this is a example query, will may change

2023-02-13 08:24 UTC, timidak requested changes
Some minor changes 👍🏻

2023-02-13 08:24 UTC, timidak commented on src/components/appointment/AppointmentDetail.tsx
> +    const countAttendees = () => {
This function is created on each render, you could refactor this with `useCallback`.

2023-02-13 08:24 UTC, timidak commented on src/components/appointment/AppointmentDetail.tsx
> +    const attendeesCount = countAttendees();
Here `useMemo` could help

2023-02-13 08:24 UTC, timidak commented on src/components/appointment/Description.tsx
> +    appointmentType?: string;
I'm not sure if a `string` is a valid type for "Type". I would rather use a union or enum.

2023-02-13 08:24 UTC, timidak commented on src/components/appointment/Header.tsx
> +    appointmentType?: string;
> I'm not sure if a string is a valid type for "Type". I would rather use a union or enum.

Same here

2023-02-13 08:24 UTC, timidak commented on src/pages/CreateAppointment.tsx
> +    const onStepOne = (id?: number) => {
Naming sounds off in my opinion.

2023-02-14 08:22 UTC, timidak approved these changes
Some last changes 👍🏻 
Rest looks pretty good!

Just merge it, when you added the changes.

2023-02-14 08:22 UTC, timidak commented on src/pages/CreateAppointment.tsx
> +                            instructions={[{ label: 'Zuordnung wählen' }, { label: 'Termine einsehen' }, { label: 'Termin hinzufügen' }]}
Labels should be added to i18n

2023-02-14 08:22 UTC, timidak commented on src/pages/CreateAppointment.tsx
> +    };
You could wrap this in a useCallback to I guess. 
```typescript
 const goToStepTwo = useCallback((id?: number) => {
        if (id) setCourseId(id);
        onNext();
    }, [setCourseId, onNext]);
```

2023-02-14 08:22 UTC, timidak commented on src/pages/create-appointment/AppointmentsView.tsx
> +// query myappointments {
What about this query now? Can we remove it?

2023-02-14 08:22 UTC, timidak commented on src/widgets/appointment/AppointmentList.tsx
> +    isStatic: boolean;
isReadOnly

2023-02-14 08:22 UTC, timidak commented on src/widgets/appointment/AssignmentTile.tsx
> +                                    alt={'Kursbild'}
For SEO and Accsessibility reasons, we should translate alt text to the language of the user. So, I would add this to i18n.

2023-02-14 08:22 UTC, timidak commented on src/widgets/appointment/appointment-list/CalendarWeek.tsx
> +    isStatic?: boolean;
isReadOnly 😸

2023-02-14 12:55 UTC, LomyW commented on src/pages/CreateAppointment.tsx
> +                            instructions={[{ label: 'Zuordnung wählen' }, { label: 'Termine einsehen' }, { label: 'Termin hinzufügen' }]}
is done in PR #128

2023-02-14 13:11 UTC, merged