Create appointment step 3
corona-school/user-app pull request #128
Opened 2023-02-14 07:49 UTC by LomyW

Ui to create an appointment with optional weekly recurring appointments.

2023-02-14 09:48 UTC, timidak requested changes
A few changes, rest looks pretty good to me!

2023-02-14 09:48 UTC, timidak commented on src/components/DatePicker.tsx
> +                    placeholder={type === 'date' ? 'Wähle ein Datum...' : '00:00'}
i18n should be used here

2023-02-14 09:48 UTC, timidak commented on src/components/appointment/AppointmentDetail.tsx
> +    const attendeesCount = useMemo(() => countAttendees(), [countAttendees]);
I guess these are the right dependencies
```suggestion
    const attendeesCount = useMemo(() => countAttendees(), [appointment.organizers, appointment.participants]);
```

2023-02-14 09:48 UTC, timidak commented on src/components/appointment/Description.tsx
> +                    {t(appointmentType === AppointmentTypes.GROUP ? 'appointment.detail.courseDescriptionHeader' : 'appointment.detail.desciptionHeader', {
typo: 'appointment.detail.desciptionHeader' -> 'appointment.detail.desc**r**iptionHeader'

2023-02-14 09:48 UTC, timidak commented on src/components/appointment/Description.tsx
>                      {appointmentType === AppointmentTypes.GROUP ? courseDescription : 'Hier kommt die appointment description.'}
'Hier kommt die appointment description.' ? Is this the final text? 😄 
Add to i18n

2023-02-14 09:48 UTC, timidak commented on src/context/AppointmentContext.tsx
> +const formReducer: Reducer<State, CreateAppointmentAction> = (state: State, action: CreateAppointmentAction) => {
createAppointmentFormReducer? ☺️

2023-02-14 09:48 UTC, timidak commented on src/pages/create-appointment/AppointmentCreation.tsx
> +            setErrors({ ...errors, title: 'Title darf nicht leer sein' });
use the i18n constants you already added here

2023-02-14 09:48 UTC, timidak commented on src/pages/create-appointment/AppointmentCreation.tsx
> +            setErrors({ ...errors, date: 'Datum darf nicht leer sein' });
> use the i18n constants you already added here

same here

2023-02-14 09:48 UTC, timidak commented on src/pages/create-appointment/AppointmentCreation.tsx
> +            setErrors({ ...errors, time: 'Zeit darf nicht leer sein' });
> use the i18n constants you already added here

same here

2023-02-14 09:48 UTC, timidak commented on src/pages/create-appointment/AppointmentCreation.tsx
> +            setErrors({ ...errors, duration: 'Dauer darf nicht leer sein' });
> use the i18n constants you already added here

same here

2023-02-14 09:48 UTC, timidak commented on src/pages/create-appointment/AppointmentCreation.tsx
> +            setErrors({ ...errors, dateNotInOneWeek: 'Datum muss in mind einer Woche sein' });
Datum muss in mind einer Woche sein -> Datum kann frühestens in einer Woche sein

2023-02-14 09:48 UTC, timidak commented on src/pages/create-appointment/AppointmentCreation.tsx
> +            setErrors({ ...errors, dateNotInOneWeek: 'Datum muss in mind einer Woche sein' });
and add to i18n ☺️

2023-02-14 13:44 UTC, LomyW commented on src/components/appointment/Description.tsx
>                      {appointmentType === AppointmentTypes.GROUP ? courseDescription : 'Hier kommt die appointment description.'}
will treat in another PR, because there are some more changes to the appointment details

2023-02-15 20:04 UTC, timidak approved these changes
LGTM 👍🏻

2023-02-17 12:20 UTC, merged