Subtitle for step two
corona-school/user-app pull request #134
Opened 2023-02-15 17:47 UTC by LomyW

for now: can't query match appointments, thats why we skip step two at the moment.

2023-02-15 20:12 UTC, timidak requested changes
Some minor changes, rest looks fine to me 👍🏻

2023-02-15 20:12 UTC, timidak commented on src/lang/appointment/de.ts
> +        insightCourseHeader: 'Deine bestehenden Termine für ',
Use a variable in i18n for the name of the course or learning buddy. This approach might work for german and english but probably won't for other languages.

2023-02-15 20:12 UTC, timidak commented on src/pages/create-appointment/AppointmentsInsight.tsx
> +// import CenterLoadingSpinner from '../../components/CenterLoadingSpinner';
remove this comment

2023-02-15 20:12 UTC, timidak commented on src/pages/create-appointment/AppointmentsInsight.tsx
> +                        {t('appointment.create.insightMatchHeader')} <Text fontWeight="bold">Leon Jackson.</Text>
Use the variable here

2023-02-15 20:12 UTC, timidak commented on src/pages/create-appointment/AppointmentsInsight.tsx
> +                        <Text fontWeight="bold">{data?.subcourse?.course?.name ? data?.subcourse?.course?.name : 'Kursname'}.</Text>
use a variable here, too.

2023-02-16 05:32 UTC, LomyW commented on src/lang/appointment/de.ts
> +        insightCourseHeader: 'Deine bestehenden Termine für ',
is there a way to make only one part of the translation bold?

2023-02-16 08:11 UTC, timidak approved these changes
Nice work 🎉

2023-02-16 08:16 UTC, merged