Feat/6 notification panel to display user notifications
corona-school/user-app pull request #14
Opened 2022-11-16 12:35 UTC by LomyW

First version of the notification panel, but with a test query. 

- Waiting for the exact notification types, so it displays always the same icon currently :)

- Also the `notificationType` and `userNotificationType` definition will still change.

2022-11-16 12:54 UTC, timidak commented on .env
> +REACT_APP_APOLLO_CLIENT_URI='https://corona-school-backend-dev.herokuapp.com'
Please remove and add it to the `.gitignore`

2022-11-16 13:01 UTC, LomyW commented on .env
> +REACT_APP_APOLLO_CLIENT_URI='https://corona-school-backend-dev.herokuapp.com'
done

2022-11-16 13:04 UTC, Jonasdoubleyou commented on .env
> +REACT_APP_APOLLO_CLIENT_URI='https://corona-school-backend-dev.herokuapp.com'
Hm, I checked it in as [advised by documentation](https://create-react-app.dev/docs/adding-custom-environment-variables), so either we adapt the `env.local` pattern, or move the `.env` to `.example.env` or something like that.

2022-11-16 13:30 UTC, timidak requested changes
First changes 😄

2022-11-16 13:33 UTC, timidak commented on src/components/Notification/NotificationPanel.tsx
> +                    ))}
So to slice the array every time seems not to be the right approach

2022-11-16 14:15 UTC, LomyW commented on src/App.tsx
> +            {/* </MatomoProvider> */}
yes. I commented out, because the user-app didn't worked with the provider.

2022-11-16 14:23 UTC, LomyW commented on src/components/Notification/MessageBox.tsx
> +          <Text>{description.slice(0, 10)}</Text>
was only for testing, because at the moment a headline doesn't exist in notifications.

2022-11-16 14:24 UTC, Jonasdoubleyou commented on src/App.tsx
> +            {/* </MatomoProvider> */}
It should work locally with REACT_APP_DISABLE_MATOMO=true (in the .env)

2022-11-16 14:28 UTC, Jonasdoubleyou commented
Maybe until this feature is ready we could branch off another branch from main (like "notification-panel"), then open regular PRs into that branch? That way we can keep main 'production ready' while you can continue working on this feature (and there are nice diffs in the PR)

2022-11-16 14:32 UTC, LomyW commented on src/pages/student/DashboardStudent.tsx
> +import NotificationAlert from '../../components/Notification/NotificationAlert'
so, this is like it was made before. The `Navigation` is called in every page separately....

2022-11-17 13:35 UTC, jeffersondarcy commented on src/components/Notification/NotificationAlert.tsx
> +              {count !== 0 && (
you could use `count && (`

2022-11-17 13:42 UTC, jeffersondarcy commented on .env
> +REACT_APP_BACKEND_URL="http://localhost:5000/apollo"
I would rename in .env.example or .env.template end add .env to .gitignore

2022-11-17 14:02 UTC, jeffersondarcy commented on src/components/Notification/NotificationPanel.tsx
> +            {showOldNotifications && (
There seems to be a code duplication to the block above, can we solve this differently, maybe with a reusable component?

2022-11-17 14:04 UTC, jeffersondarcy commented on src/hooks/useNotificationPanel.tsx
> +        sentAt
currently it is createdAt, but I need to re-evaluate

2022-11-17 14:06 UTC, jeffersondarcy commented on src/types/lernfair/Notification.ts
> +  TYP1 = 'Type 1',
TYP or TYPE?

2022-11-17 14:36 UTC, LomyW commented on src/types/lernfair/Notification.ts
> +  TYP1 = 'Type 1',
will change when I MessageTypes are finally defined.

2022-11-17 14:36 UTC, LomyW commented on src/components/Notification/NotificationPanel.tsx
> +            {showOldNotifications && (
thought about it too.

2022-11-18 12:11 UTC, LomyW commented
opened new PR #15

2022-11-18 12:11 UTC, closed without merging