Feat/6 notification panel
corona-school/user-app pull request #15
Opened 2022-11-18 11:52 UTC by LomyW

**User can display dummy notifications on a panel by click on a bell button.**
as discussed: NotificationPanel with test notification types.

2022-11-18 12:21 UTC, jeffersondarcy commented on src/components/Notification/MessageBox.tsx
> +  isToast?: boolean
maybe it's better to call it `displayTime` or `showTime` to make it more universal

2022-11-18 12:24 UTC, jeffersondarcy commented on src/components/Notification/MessageBox.tsx
> +          <Box p={'8px'}>{getIconForCategory(notification.messageType)}</Box>
the naming looks a bit inconsistent with mixing of type and category, maybe it's better to rename the function to just `getIcon`

2022-11-18 12:26 UTC, jeffersondarcy commented on src/components/Notification/NotificationAlert.tsx
> +    <>
you don't need the Fragment <> because everything is wrapped inside Popover anyway

2022-11-18 12:36 UTC, jeffersondarcy commented on src/components/Notification/NotificationAlert.tsx
> +              <Button {...triggerProps} bgColor="">
props spreading should be avoided if possible

2022-11-18 12:40 UTC, LomyW commented on src/components/Notification/NotificationAlert.tsx
> +        trigger={triggerProps => {
its from native base. But yes it is possible to trigger a separated component.

2022-11-18 13:00 UTC, jeffersondarcy commented on src/components/Notification/MessageBox.tsx
> +const MessageBox: React.FC<Props> = ({ userNotification, isToast, isRead }) => {
should isToast and isRead have explicit default values?

2022-11-18 13:01 UTC, LomyW commented on src/components/Notification/MessageBox.tsx
> +const MessageBox: React.FC<Props> = ({ userNotification, isToast, isRead }) => {
why?

2022-11-18 13:03 UTC, jeffersondarcy commented on src/components/Notification/NotificationPanel.tsx
> +                  {data.me.concreteNotifications.map(
it woul look nicer ond hide implementation details if you could just do `concreteNotifications.map` without `data.me`

2022-11-18 13:06 UTC, jeffersondarcy commented on src/hooks/useNotificationPanel.tsx
> +const useTimeDifference = (timestamp: string, isToast?: boolean) => {
this looks for me like a helper function, not a hook

2022-11-18 13:11 UTC, jeffersondarcy commented on src/hooks/useNotificationPanel.tsx
> +import { gql, useQuery } from '@apollo/client'
I think the file name useNotificationPanel.tsx is misleading as there is no hook with such name, also the extention should be "ts" as there is no JSX

2022-11-18 13:14 UTC, LomyW commented on src/hooks/useNotificationPanel.tsx
> +const useTimeDifference = (timestamp: string, isToast?: boolean) => {
its a hook because of the useTranslation hook

2022-11-18 13:22 UTC, LomyW commented on src/hooks/useNotificationPanel.tsx
> +import { gql, useQuery } from '@apollo/client'
renamed it to useNotifications.ts

2022-11-18 13:25 UTC, LomyW commented on src/hooks/useNotificationPanel.tsx
> +const useTimeDifference = (timestamp: string, isToast?: boolean) => {
added getTimeDifference to the notification-helper

2022-11-18 13:28 UTC, LomyW commented on src/hooks/useNotificationPanel.tsx
> +const useTimeDifference = (timestamp: string, isToast?: boolean) => {
renamed it to useTimeAgoTranslation

2022-11-21 09:44 UTC, timidak requested changes
Some minor changes left, but nice work 🎉 
One point I also saw is that we have no margin or padding to the edge of the browser, when opening the notifications panel. I guess this should be tackled as well.

2022-11-21 09:44 UTC, timidak commented on src/components/Notification/MessageBox.tsx
> +        <Box>{!displayTime && <TimeIndicator createdAt={createdAt} />}</Box>
Why are we rendering the `<TimeIndicator />` when displayTime is false?
I would suggest to do it the other way around

2022-11-21 09:44 UTC, timidak commented on src/components/Notification/NotificationAlert.tsx
> +            <Text fontSize="10" color="white">
Can we use xs, md or other standardized values for fontSize?

2022-11-21 09:44 UTC, timidak commented on src/components/Notification/NotificationAlert.tsx
> +        <Button onPress={onPress} ref={ref} bgColor="">
remove the `bgColor` prop if it's empty

2022-11-21 09:44 UTC, timidak commented on src/components/Notification/TimeIndicator.tsx
> +      {/* {time && <Text fontSize="12px">{t(time.text, time?.options)}</Text>} */}
Can this be removed? 🙂

2022-11-21 09:44 UTC, timidak commented on src/components/SettingsButton.tsx
> +    <Button bgColor="" ml={-4} onPress={() => navigate('/settings')}>
Can we remove the background color prop? And is it possible to use the margin on the other side, rather than using a negative margin?

2022-11-21 09:44 UTC, timidak commented on src/hooks/useNotifications.ts
> +const useNotifications = (skip?: number, take?: number) => {
I don't think we need `skip?` and `take?`, maybe we'll need it later, but I would remove it for now

2022-11-21 09:44 UTC, timidak commented on src/hooks/useNotifications.ts
> +  return { data, notifications, loading, error, refetch }
You should either use an effect here or do not destructure the notifications. Otherwise the notifications are not updated properly.
In addition, I wouldn't just return data, but only the notifications.
```suggestion
  const { data, loading, error, refetch } = useQuery(userNotificationQuery)
  
  const [notifications, setNotifications] = useState([]);
  
  useEffect(() => {
    if(!loading && !error) {
      setNotifications(data?.me?.concreteNotifications);
    }
  }, [loading]);
  
  return { notifications, loading, error, refetch }
```

2022-11-21 15:02 UTC, merged