More information to coursecard
corona-school/user-app pull request #201
Opened 2023-03-21 09:54 UTC by LomyW

it must be clarified which card variant is shown where 😄

2023-03-21 10:30 UTC, timidak requested changes
Some changes to be made ☺️

2023-03-21 10:30 UTC, timidak commented on src/pages/pupil/Dashboard.tsx
> +    const getTrafficStatusText = (subcourse: Subcourse | LFSubCourse): string => {
Maybe a useCallback?

2023-03-21 10:30 UTC, timidak commented on src/pages/student/CourseGroups.tsx
> +    const getTrafficStatusText = (subcourse: Subcourse | LFSubCourse): string => {
This is code duplication just move this function to a util folder or sth similar and use it for both components

2023-03-21 10:30 UTC, timidak commented on src/pages/student/CourseGroups.tsx
> +            showStatus={inPast ? false : true}
just pass `!inPast` that does exactly what you want

2023-03-21 10:30 UTC, timidak commented on src/pages/student/CourseGroups.tsx
> +            showCourseTraffic={subcourse.published && !inPast ? true : false}
`subcourse.published && inPast`?

2023-03-21 10:30 UTC, timidak commented on src/pages/student/StudentGroup.tsx
> +                                                        pastCourses={pastSubcourses as Subcourse[]}
Casting might be unsafe here, whats the type? maybe `undefined`? Then you should include this to the props and programmatically decide what to do if it's `undefined`

2023-03-21 10:30 UTC, timidak commented on src/pages/student/StudentGroup.tsx
> +                                                    />
> Casting might be unsafe here, whats the type? maybe undefined? Then you should include this to the props and programmatically decide what to do if it's undefined

Same here

2023-03-21 10:30 UTC, timidak commented on src/pages/subcourse/AllSubcourses.tsx
> +            showSchoolclass={user?.pupil ? true : false}
use a boolean cast shorthand (`!!`) or `Boolean(user?.pupil)`

2023-03-21 12:33 UTC, LomyW commented on src/widgets/AppointmentCard.tsx
> +                <Card flexibleWidth={isTeaser || isGrid ? true : false} width={isTeaser ? 'full' : '300px'} variant={isTeaser ? 'dark' : 'normal'}>
without the width, the date is separated by a newline

2023-03-22 12:43 UTC, timidak reviewed
Some suggestions 👍🏻

2023-03-22 12:43 UTC, timidak commented on src/pages/student/DashboardStudent.tsx
> +    const getTrafficStatusText = (subcourse: Subcourse | LFSubCourse): string => {
why a union of `Subcourse | LFSubCourse` one should be sufficient

2023-03-22 12:43 UTC, timidak commented on src/pages/student/DashboardStudent.tsx
> +                                                key={`appointment-${index}`}
Do we have something like the `appointmentId` so that we can use it here?
Because using array indexes as keys can cause bugs in React. [This article](https://kentcdodds.com/blog/understanding-reacts-key-prop) clarifies that very good.

2023-03-22 12:43 UTC, timidak commented on src/widgets/CourseTrafficLamp.tsx
> +                                ? t('single.global.status.last', { seatsLeft: seatsLeft })
What if seatsLeft is `undefined`?

2023-03-24 14:10 UTC, timidak approved these changes
Looks good to me 👍🏻

2023-03-24 14:33 UTC, timidak approved these changes
and again 👍🏻

2023-03-24 14:33 UTC, merged