Feat-5 message box
corona-school/user-app pull request #22
Opened 2022-11-21 15:18 UTC by jeffersondarcy

do not merge, just a bug demonstration

2022-11-22 22:24 UTC, timidak requested changes
Some changes, just ping me when the PR is ready for review. 🙂

2022-11-22 22:24 UTC, timidak commented on src/components/WebsocketClient.tsx
> +export const WebsocketClient = () => {
I provided a first draft to @LomyW with an interface, a ws client implementation and a possible switch for a React Native implementation. Why aren't you using this?

2022-11-22 22:24 UTC, timidak commented on src/hooks/NotificationsProvider.tsx
> +type Notification = Partial<UserNotification>
Why a Partial?

2022-11-22 22:24 UTC, timidak commented on src/components/WebsocketClient.tsx
> +    const socket = new WebSocket("wss://ws.kraken.com");
Keep in mind that the connection can only be done when the user is logged in. Because you'll need the `Session token` to authenticate at the websocket server.

2022-11-22 22:24 UTC, timidak commented on src/hooks/NotificationsProvider.tsx
> +    const [{notifications}, setState] = useState<State>({notifications: []})
What about: 
```suggestion
    const [notifications, setState] = useState<State>([])
```

The state would then be `Notification[]`

2022-11-22 22:24 UTC, timidak commented on src/App.tsx
> +function App () {
Where does this whitespace come from? Some formatter?

2022-11-22 22:24 UTC, timidak commented on src/hooks/NotificationsProvider.tsx
> +      // fetch notification from graphql
I don't think you can fetch the notification here, if you use a query hook of Apollo.

2022-11-23 09:45 UTC, jeffersondarcy commented on src/hooks/NotificationsProvider.tsx
> +type Notification = Partial<UserNotification>
that was only for testing purposes, will change it to "full"

2022-11-23 09:51 UTC, jeffersondarcy commented on src/hooks/NotificationsProvider.tsx
> +      // fetch notification from graphql
I was thinking about mowing it to WS Client Component - one more reason for this

2022-11-23 16:39 UTC, jeffersondarcy commented on src/components/WebsocketClient.tsx
> +    const socket = new WebSocket("wss://ws.kraken.com");
will implement this logic later when dealing with real backend

2022-11-23 16:42 UTC, jeffersondarcy commented on src/App.tsx
> +function App () {
fixed

2022-11-28 11:05 UTC, timidak requested changes
Some changes to be made

2022-11-28 11:05 UTC, timidak commented on src/hooks/NotificationsProvider.tsx
> +type State = { notifications: Notification[], notificationIds: number[] }
Why do we need the notifications and the ids. Aren't the ids enough?

2022-11-28 11:05 UTC, timidak commented on src/hooks/NotificationsProvider.tsx
> +    }
This feels a little bit like React 15 for me, why aren't we using two separate `useState` functions for this?

2022-11-30 14:43 UTC, jeffersondarcy commented on src/hooks/NotificationsProvider.tsx
> +type State = { notifications: Notification[], notificationIds: number[] }
first websocket sets the id, than the data component fetches the message(notification). when message updates the toast appears. notification id change triggers data fetching

2022-11-30 14:45 UTC, jeffersondarcy commented on src/hooks/NotificationsProvider.tsx
> +    }
true, I will change this

2022-11-30 14:58 UTC, jeffersondarcy commented on src/components/WebsocketClient.tsx
> +    const host = 'wss://ws.localhost:5000'
added a separate env param

2022-11-30 14:58 UTC, jeffersondarcy commented on src/hooks/NotificationsProvider.tsx
> +    }
done

2022-11-30 15:00 UTC, jeffersondarcy commented on src/components/NotificationsData.tsx
> +}
I think in future the data will be used by notification panel too

2022-11-30 15:00 UTC, jeffersondarcy commented on src/types/Websocket.ts
> +class BrowserWebsocketClient implements WebSocketClient {
moved to lib

2022-11-30 18:22 UTC, Jonasdoubleyou commented on .env.example
> +REACT_APP_UNSPLASH=""
Document in README (`cp .env.example .env`), also the default dev workflow should point to the development backend (as the majority does not have a local backend running). Can both be done somewhen ...

2022-11-30 18:22 UTC, Jonasdoubleyou commented on src/components/NotificationsProvider.tsx
> +    const setValidatedMessage = (message: UserNotification | unknown) => {
`useCallback`, otherwise the ContextProvider rerenders pretty often, no?

2022-11-30 18:22 UTC, Jonasdoubleyou commented on src/components/ToastNotifications.tsx
> +    if (typeof message === 'object') showInAppMessage(message, isMobile)
if (message != null) is clearer IMO

2022-11-30 18:22 UTC, Jonasdoubleyou commented on src/lib/Websocket.ts
> +const WSClient = BrowserWebsocketClient
Nice!

2022-12-01 09:27 UTC, timidak requested changes
Some other changes and suggestions 😄

2022-12-01 09:27 UTC, timidak commented on src/components/NotificationsData.tsx
> +}
Do we need this in a separate Component. How about adding this to the ToastNotifications?

2022-12-01 09:27 UTC, timidak commented on src/components/NotificationsData.tsx
> +  }, [data, error])
Adding the loading state of apollo here might be easier and less expensive I'd say.

2022-12-01 09:27 UTC, timidak commented on src/components/WebsocketClient.tsx
> +      const url = encodeURI(`${process.env.REACT_APP_WEBSOCKET_URL}?id=${userId}&token=${getSessionToken()}`)
I would add the WEBSOCKET url to the config.ts and use it from there imho, this makes the dependency clearer

2022-12-01 09:27 UTC, timidak commented on src/hooks/useConcreteNotification.ts
> +      skip: typeof id !== 'number'
You're skipping here! Nice!

2022-12-01 09:27 UTC, timidak commented on src/components/WebsocketClient.tsx
> +  }, [sessionState, userId, setConcreteNotificationId]);
You'll need to wrap the `setConcreteNotificationId` in a useCallback in the Provider so that re-running the effect is avoided because of reference changes.

2022-12-01 09:53 UTC, Jonasdoubleyou commented on src/components/WebsocketClient.tsx
> +      const url = encodeURI(`${process.env.REACT_APP_WEBSOCKET_URL}?id=${userId}&token=${getSessionToken()}`)
Good point, also this is actually needed as we build the frontend only once (where REACT_APP_ is inlined into the bundle) and then use it both for staging & production. Please also introduce RUNTIME_WEBSOCKET_URL (like RUNTIME_BACKEND_URL)

2022-12-01 10:32 UTC, jeffersondarcy commented on .env.example
> +REACT_APP_UNSPLASH=""
removed the values and renamed to .env.template. also added a sentence in readme

2022-12-01 15:05 UTC, jeffersondarcy commented on src/components/WebsocketClient.tsx
> +  }, [sessionState, userId, setConcreteNotificationId]);
moved to hook

2022-12-01 15:10 UTC, jeffersondarcy commented on src/components/WebsocketClient.tsx
> +      const url = encodeURI(`${process.env.REACT_APP_WEBSOCKET_URL}?id=${userId}&token=${getSessionToken()}`)
done

2022-12-01 15:13 UTC, jeffersondarcy commented on src/components/NotificationsData.tsx
> +  }, [data, error])
loading is checked in useConcreteNotification.ts now

2022-12-01 15:13 UTC, jeffersondarcy commented on src/components/NotificationsData.tsx
> +}
fixed

2022-12-01 15:15 UTC, jeffersondarcy commented on src/components/NotificationsProvider.tsx
> +    const setValidatedMessage = (message: UserNotification | unknown) => {
useState is removed now

2022-12-01 20:18 UTC, timidak reviewed
Some last questions and suggestions 👍🏼

2022-12-01 20:18 UTC, timidak commented on src/hooks/useConcreteNotification.ts
> +      skip: id == null
```suggestion
      skip: !id
```
This should handle undefined, null & empty string. 🙂

2022-12-01 20:18 UTC, timidak commented on src/hooks/useConcreteNotification.ts
> +    if (!loading && !error && data && isMessageValid(data?.concrete_notification)) {
I assume isMessageValid should return invalid if data is nullish so the third element is unnecessary, i guess.

2022-12-01 20:18 UTC, timidak commented on src/hooks/useConcreteNotification.ts
> +  if (message === null) return false
Can it also be undefined?

2022-12-02 09:35 UTC, jeffersondarcy commented on src/components/ToastNotifications.tsx
> +  const message = useConcreteNotificationMessage(concreteNotificationId)
useConcreteNotification hook returns only message data now

2022-12-02 09:37 UTC, jeffersondarcy commented on src/components/useIncomingWSConcreteNotificationId.ts
> +      const url = encodeURI(`${process.env.REACT_APP_WEBSOCKET_URL}?id=${userId}&token=${getSessionToken()}`)
this was the right file, but now I renamed it

2022-12-02 09:42 UTC, jeffersondarcy commented on src/components/useIncomingWSConcreteNotificationId.ts
> +type State = number | null
fixed

2022-12-02 09:44 UTC, jeffersondarcy commented on src/hooks/useConcreteNotificationMessage.ts
> +  }, [data, error])
useConcreteNotification uses loading now

2022-12-02 09:52 UTC, jeffersondarcy commented on src/hooks/useConcreteNotification.ts
> +  if (message === null) return false
fixed

2022-12-02 09:53 UTC, jeffersondarcy commented on src/hooks/useConcreteNotification.ts
> +    if (!loading && !error && data && isMessageValid(data?.concrete_notification)) {
isMessageValid was not checking for undefined and I had an error when the backend was down, but now it should be unnecessary

2022-12-02 10:25 UTC, merged