InAppMessages component
corona-school/user-app pull request #24
Opened 2022-11-22 13:27 UTC by LomyW

for testing:
- import function into i.e. `Navigator` in a `useEffect` with `setInterval`
- props you need is a `notification` object and `isMobile`
- for `isMobile` use the `useBreakpointValue` hook from `native base`
`const isMobile = useBreakpointValue({
base: true,
lg: false 
})`

2022-11-22 22:10 UTC, timidak requested changes
Some minor changes.
Something we should try to avoid are ["magic numbers"](https://en.wikipedia.org/wiki/Magic_number_(programming)) or hardcoded values as props.
Everything else looks pretty good 👍🏼

2022-11-22 22:10 UTC, timidak commented on src/components/Notification/NotificationPanel.tsx
> +            <Box maxH={420}>
Would also save those "magic numbers" into variables. `panelMaxHeightAllDevices` or something similar.

2022-11-22 22:10 UTC, timidak commented on src/components/Notification/MessageBox.tsx
> +        {displayTime && (
Would call the prop something like `isStandalone` and if it's `!isStandalone` then the time is rendered and the width is different.

2022-11-23 06:42 UTC, LomyW commented on src/components/Notification/NotificationAlert.tsx
> +  const BadgeAlign = useBreakpointValue({
wasn't sure about that, because saw both variants in the existing components. 
So should we agree on `camelCase`?

2022-11-23 06:48 UTC, LomyW commented on src/components/Notification/NotificationPanel.tsx
> +  const PanelMarginLeft = useBreakpointValue({
changed to `camelCase`

2022-11-23 06:49 UTC, LomyW commented on src/components/Notification/NotificationPanel.tsx
> +  const PanelMarginRight = useBreakpointValue({
changed to `camelCase`

2022-11-23 13:51 UTC, jeffersondarcy commented on src/hooks/useConcreteNotification.ts
> +    concrete_notification(concreteNotificationId: $id) {
can this be a list of ids? or do you need to change the backend implementation first?

2022-11-23 13:54 UTC, jeffersondarcy approved these changes
I have commented a minor thing, but you can merge already

2022-11-23 13:59 UTC, merged