Fix/696 match card design
corona-school/user-app pull request #250
Opened 2023-04-19 14:59 UTC by LucasFalkowsky

All MatchCards have been equalized so that the design is tight.

2023-04-19 19:02 UTC, timidak commented
@LucasFalkowsky could you please set the target branch to one of our feature branches? The diff is outta control 😄

2023-04-25 12:59 UTC, LomyW requested changes
some minor things, rest looks good to me 👍

2023-04-25 12:59 UTC, LomyW commented on src/pages/match/Matches.tsx
> +                    paddingRight={!isMobile && index % 2 === 0 ? space['0.5'] : 0}
do we need the modulo here? 🙂

2023-04-25 12:59 UTC, LomyW commented on src/pages/student/DashboardStudent.tsx
> +                                                        paddingRight={!isMobile && index % 2 === 0 ? space['0.5'] : 0}
also here?

2023-04-25 12:59 UTC, LomyW commented on src/pages/create-appointment/AppointmentAssignment.tsx
> +                                        {' '}
remove

2023-04-26 09:00 UTC, LucasFalkowsky commented on src/pages/match/Matches.tsx
> +                    paddingRight={!isMobile && index % 2 === 0 ? space['0.5'] : 0}
this was a pragmatic way of coding the gap inbetween the cards without changing the whole architecture, since it was programmed with a Box not a stack.

What is your opinion on this?

2023-04-26 09:05 UTC, LomyW commented on src/pages/match/Matches.tsx
> +                    paddingRight={!isMobile && index % 2 === 0 ? space['0.5'] : 0}
think its ok, but also I think its prettier if it is a stack or?

2023-04-26 10:01 UTC, merged