Integrated Chat
corona-school/user-app pull request #260
Opened 2023-05-10 09:46 UTC by LomyW

Feature branch for the integrated chat

- [x]  installed TalkJS via npm
- [x] chat view was created 
- [x] skeleton for chat components
- [x] custom theming in TalkJS
- [x] added new navigation bar (include `chat` item, `help center` on navbar)

2023-07-07 12:35 UTC, LomyW commented on src/pages/Chat.tsx
> +                    <FloatingActionButton mr={marginRight} mt={marginTop} handlePress={handleNewChatPress} place={'bottom-right'} icon={<LFAddChatIcon />} />
change position of add chat button

2023-07-07 12:35 UTC, LomyW commented on src/pages/SingleMatch.tsx
> +        <AsNavigationItem path="matching">
fixes the problem on navigate back from chat to match page

2023-07-07 12:36 UTC, LomyW commented on src/pages/student/SingleCourseStudent.tsx
> +                        <AppointmentsEmptyState title={t('appointment.empty.noAppointments')} subtitle={t('appointment.empty.noAppointmentsDesc')} />
had the problem, if a subcourse has no appointments, the app failed. So no we show the `empty state` instead

2023-07-07 12:37 UTC, LomyW commented on src/pages/student/single-course/StudentCourseButtons.tsx
> +                    <OpenCourseChatButton
fix: integrate new chat feature instead of old email contact feature

2023-08-11 12:17 UTC, Jonasdoubleyou commented
(please wait till Tuesday next week, we want to bring some other stuff this weekend and might need to deploy)

2023-08-11 12:17 UTC, Jonasdoubleyou requested changes
(blocking submit)

2023-08-14 17:44 UTC, Jonasdoubleyou commented on package.json
> +        "talkjs": "^0.15.9",
Like all the other dependencies here except for compression/express, this is a devDependency ...

2023-08-14 17:46 UTC, Jonasdoubleyou commented on src/components/chat/NewChat.stories.mdx
> +<Meta title="Chat/ContactList" component={NewChat} />
The component is ContactList, so should be the name of the file

2023-08-14 17:48 UTC, Jonasdoubleyou commented on src/context/ChatContext.tsx
> +
I guess this will conflict with https://github.com/corona-school/user-app/pull/329, where we need to exclude screeners from loading the Chat info

2023-08-17 15:16 UTC, Jonasdoubleyou submitted a review, later dismissed

2023-08-18 06:45 UTC, Jonasdoubleyou submitted a review, later dismissed

2023-08-18 06:53 UTC, Jonasdoubleyou approved these changes

2023-08-19 14:24 UTC, merged