Feat/7 (un)read messages
corona-school/user-app pull request #30
Opened 2022-11-29 14:45 UTC by LomyW

NOTE: 
- change useEffect dependency in `NotificationAlert` to contextNotifications, when `Notification Context` is read
- `createdAt` will be in future `sentAt`, hence the renaming

2022-12-01 16:39 UTC, jeffersondarcy commented on src/Navigator.tsx
> +import ResetPassword from './pages/ResetPassword'
it's not used, right?

2022-12-01 16:50 UTC, jeffersondarcy commented on src/components/Notification/NotificationAlert.tsx
> +  const { notifications, refetch } = useNotifications()
`useNotifications` hook name is misleading as it returns concreteNotifications and there is another hook useConcreteNotification with same query only parametrised with id
but it's not part of this PR as the hooks were already there

2022-12-01 16:51 UTC, jeffersondarcy commented on src/components/Notification/NotificationAlert.tsx
> +    notifications.map(noti =>
noti :)

2022-12-01 16:57 UTC, jeffersondarcy commented on src/hooks/useLastTimeCheckedNotifications.ts
> +      student {
would it be possible to use a parameter for "student" or "pupil" in queries?

2022-12-01 17:07 UTC, jeffersondarcy commented on src/components/Notification/NotificationPanel.tsx
> +  const { loading } = useNotifications()
this doesn't look right for me, you are passing notifications in props, but using the hook here again. I assume it will query the notifications here again and show the loading state of this query

2022-12-01 17:14 UTC, jeffersondarcy commented on src/components/Notification/NotificationPanel.tsx
> +    for (let i = notificationsToRender.length; i < 5; i++) {
are you showing 5 "old" notifications? can you may be do it in a function with a speaking name? because otherwise you need to "reverse-engineer" to understand. Do we need to limit the number of old messages or would it be better to have max number of messages. 
for example max=10 -> if there are already 10 new, we don't show any old
but we can show all new without limit

2022-12-01 17:16 UTC, jeffersondarcy commented on src/helper/notification-helper.tsx
> +const setReadOrUnread = (sentAt: string, lastOpen: string) => {
maybe `isNew` would be a better name? the function is not setting anything

2022-12-01 17:19 UTC, jeffersondarcy commented on src/pages/CourseArchive.tsx
> +import NotificationAlert from '../components/notification/NotificationAlert'
this is not used

2022-12-01 17:20 UTC, jeffersondarcy commented on src/pages/AppointmentsArchive.tsx
> +import NotificationAlert from '../components/notification/NotificationAlert'
not used and path is wrong

2022-12-01 17:20 UTC, jeffersondarcy commented on src/pages/DigitaleTools.tsx
> +import NotificationAlert from '../components/notification/NotificationAlert'
same as above

2022-12-01 17:21 UTC, jeffersondarcy commented on src/pages/Explore.tsx
> +import NotificationAlert from '../components/notification/NotificationAlert'
same as above

2022-12-01 17:21 UTC, jeffersondarcy commented on src/pages/LearningPartnerArchive.tsx
> +import NotificationAlert from '../components/notification/NotificationAlert'
same

2022-12-01 17:21 UTC, jeffersondarcy commented on src/pages/QuickStart.tsx
> +import NotificationAlert from '../components/notification/NotificationAlert'
same

2022-12-01 17:21 UTC, jeffersondarcy commented on src/pages/UserProfile.tsx
> +import NotificationAlert from '../components/notification/NotificationAlert'
same

2022-12-01 17:22 UTC, jeffersondarcy commented on src/widgets/InAppMessage.tsx
> +import MessageBox from '../components/notification/MessageBox'
same

2022-12-01 17:22 UTC, jeffersondarcy commented on src/pages/student/StudentGroupSupport.tsx
> +import NotificationAlert from '../../components/notification/NotificationAlert'
same

2022-12-01 17:22 UTC, jeffersondarcy commented on src/pages/student/StudentGroup.tsx
> +import NotificationAlert from '../../components/notification/NotificationAlert'
same

2022-12-01 17:22 UTC, jeffersondarcy commented on src/pages/student/RequestMatch.tsx
> +import NotificationAlert from '../../components/notification/NotificationAlert'
same

2022-12-01 17:23 UTC, jeffersondarcy commented on src/pages/student/ProfileStudent.tsx
> +import NotificationAlert from '../../components/notification/NotificationAlert'
same

2022-12-01 18:02 UTC, LomyW commented on src/components/Notification/NotificationAlert.tsx
> +  const { notifications, refetch } = useNotifications()
will be updated with the integration of the context

2022-12-01 18:02 UTC, LomyW commented on src/components/Notification/NotificationAlert.tsx
> +    notifications.map(noti =>
thanks 😅

2022-12-01 18:28 UTC, LomyW commented on src/components/Notification/NotificationPanel.tsx
> +    for (let i = notificationsToRender.length; i < 5; i++) {
showing all new notifications. AFAIK the limit is 100 (from backend) and concreteNotifications will be deleted after 3 months. Please correct me if I'm wrong. 😄

2022-12-01 18:34 UTC, LomyW commented on src/pages/AppointmentsArchive.tsx
> +import NotificationAlert from '../components/notification/NotificationAlert'
wanted to rename the folder /Notification to lowercase /notification. 😀

2022-12-01 20:01 UTC, timidak requested changes
Some changes to do 🙁

2022-12-05 12:59 UTC, jeffersondarcy commented on src/components/notifications/NotificationAlert.tsx
> +        {count > 0 && (
just `count` should work too:  
`{count && (`

2022-12-05 12:59 UTC, jeffersondarcy commented on src/components/notifications/NotificationAlert.tsx
> +        {count > 0 && (
```suggestion
        {count (
```

2022-12-05 13:00 UTC, jeffersondarcy commented on src/components/notifications/NotificationAlert.tsx
> +        {count > 0 && (
```suggestion
        {count && (
```

2022-12-05 13:12 UTC, jeffersondarcy commented on src/components/notifications/NotificationAlert.tsx
> +    refetch()
I am not sure that we should use refetch here, when you look at docs examples provided you rather trigger refetch on click

2022-12-05 13:20 UTC, jeffersondarcy commented on src/helper/notification-helper.tsx
> +const getTimeDifferenceByTimestamp = (timestamp: string) => {
should the parameter be called a `timeString`? because for me "timestamp" is usually a number. Than function could be called just `getTimeDiff`

2022-12-05 13:34 UTC, jeffersondarcy commented on src/hooks/useConcreteNotification.ts
> +  console.log('[uCN] concrete notification', concreteNotification)
was this log for debugging or should it stay?

2022-12-06 15:54 UTC, jeffersondarcy commented on src/components/notifications/NotificationAlert.tsx
> +const NotificationAlert: React.FC = () => {
the name is misleading, because this component is a container for the whole "Notification Panel" logic, the `NotificationPanel` component might be called just `NotificationsList` because it is not doing much

2022-12-19 08:01 UTC, LomyW reviewed
well done! @jeffersondarcy  🎉

2022-12-19 10:52 UTC, closed without merging

2022-12-19 10:53 UTC, jeffersondarcy commented
replaced by https://github.com/corona-school/user-app/pull/66