Fix: Entering appointment infos on safari
corona-school/user-app pull request #360
Opened 2023-09-12 10:06 UTC by LomyW

### Description
Select element takes focus from input element on react native web on Safari browser

### Done
- [x] Added a select specific for safari

### Tested
- [x] Safari
- [x] Firefox
- [x] Chrome

2023-09-12 11:25 UTC, timidak commented
@LomyW is this branch up to date with main? 
Seems like the checks are failing, because of the graphql validation.

2023-09-13 11:40 UTC, LomyW commented
> @LomyW is this branch up to date with main? Seems like the checks are failing, because of the graphql validation.

yes it is up to date with main.

2023-11-02 17:55 UTC, dhenkel92 submitted a review, later dismissed

2023-11-03 06:25 UTC, timidak requested changes
Just a few general things, could you please test it again on every browser, after you implemented the changes.

2023-11-03 06:25 UTC, timidak commented on src/widgets/SafariSelect.tsx
> +const SafariSelect = (props: any) => {
`props` shouldn't be typed as any. Use the props the `NBSelect` uses.
Also, `SafariSelect` seems like it's only used for Safari?

2023-11-03 06:25 UTC, timidak commented on src/widgets/SafariSelect.tsx
> +export { SafariSelect };
Why do we have to export statements? I'd say either try the named export or the default one.

2023-11-03 06:25 UTC, timidak commented on src/widgets/SafariSelect.tsx
> +const SafariSelect = (props: any) => {
I would add some additional documentation, why we had do build this select, maybe with a link to the issues and a short description of the problem as JS/TS-Doc.

2023-11-07 14:33 UTC, timidak approved these changes
LGTM 👍🏻

2023-11-07 14:40 UTC, merged