979 achievement card
corona-school/user-app pull request #396
Opened 2023-11-03 07:29 UTC by LucasFalkowsky

closes https://github.com/corona-school/project-user/issues/979

2023-11-06 10:46 UTC, LucasFalkowsky commented on .storybook/style.css
> +@font-face {
This does not work. If you find a way to make it work I would be thrilled.

2023-11-06 10:47 UTC, LucasFalkowsky commented on src/components/achievements/achievementCard/achievementCard.tsx
> +};
The types will be moved to a separate file in branch #978

2023-11-06 10:48 UTC, LucasFalkowsky commented on src/components/achievements/achievementCard/achievementCardMobile.tsx
> +};
Same here. Types were moved to a separate file in #978

2023-11-06 10:54 UTC, LucasFalkowsky commented on src/components/achievements/achievementCard/animatedShine.tsx
> +const AnimatedShine: React.FC<AnimatedShineProps> = ({ props, isMobile }) => {
This Component is used to animate a shiny particle

2023-11-06 10:54 UTC, LucasFalkowsky commented on src/components/achievements/achievementCard/newAchievementShine.tsx
> +const NewAchievementShine: React.FC<NewAchievementShineProps> = ({ isMobile }) => {
In this component we generate the shiny particles. It is not done random, to prevent particles from overlapping. Like this we have more control on where the animated Elements are spawning.

2023-11-06 16:59 UTC, LomyW requested changes
Nice work, all in all some changes to make. We should try to use components from native base and also work with the breakpoint values. Also make sure to name the components correctly, use the previous components as a guide. (P.S. I love the sparkling) 😇

2023-11-06 16:59 UTC, LomyW commented on src/components/achievements/achievementCard/achievementCardMobile.tsx
> +const AchievementCardMobile: React.FC<AchievementCardMobileProps> = ({
We don't actually build our own components for mobile. Please use a component and then build it responsive with `useBreakpointValue`. I would like to do the same with achievements. Could you please rebuild the `AchievementCard` component so that it also works on mobile?

2023-11-06 16:59 UTC, LomyW commented on src/components/achievements/achievementCard/animatedShine.tsx
> +    const thresholdY = isMobile ? -35 : -70;
you could also use breakpoint value here, to switch between mobile and desktop: ```const isMobile = useBreakpointValue({
        base: true,
        lg: false,
    });```

2023-11-06 16:59 UTC, LomyW commented on src/components/achievements/achievementCard/animatedShine.tsx
> +            <PresenceTransition
nice ✨

2023-11-06 16:59 UTC, LomyW commented on src/components/achievements/achievementCard/newAchievementShine.tsx
> +    const getShineProps = (index: number): AnimatedShineProps => {
also here, please use breakpoint values

2023-11-06 16:59 UTC, LomyW commented on src/components/achievements/polaroid/getPolaroidImage.tsx
> +const PolaroidImageContainer: React.FC<PolaroidImageContainerProps> = ({ image, alternativeText, isMobile }) => {
Please don't name component files like a function. Always use the real component name.

2023-11-06 16:59 UTC, LomyW commented on src/components/achievements/polaroid/emptyPolaroidField.tsx
> +        <div
Also here: try to use no divs, try to find a native base component

2023-11-06 16:59 UTC, LomyW commented on src/components/achievements/polaroid/completePolaroid.tsx
> +const CompletePolaroid: React.FC<CompletePolaroidProps> = ({ image, alternativeText, isMobile }) => {
Is this an image component?

2023-11-06 16:59 UTC, LomyW commented on src/components/achievements/progressIndicators/indicatorBar.tsx
> +            <Box alignItems={'left'} height={'8px'} width={isMobile ? '90%' : '100%'} backgroundColor={Theme.colors.gray[300]} borderRadius={'4px'}>
Could you please check if we can reuse the progress bar from native base here? https://docs.nativebase.io/progress

2023-11-06 16:59 UTC, LomyW commented on .storybook/style.css
> +@font-face {
To be honest, I still don't have a solution for the problem with the font in Storybook. If it doesn't work, could you please expand the workaround?

2023-11-06 16:59 UTC, LomyW reviewed
Nice work, all in all some changes to make. We should try to use components from native base and also work with the breakpoint values. Also make sure to name the components correctly, use the previous components as a guide. (P.S. I love the sparkling) 😇

2023-11-07 08:38 UTC, LucasFalkowsky commented on src/components/achievements/achievementCard/achievementCard.tsx
> +        <div
There apparently is no way to do a inner shadow with native base components. Therefore I split the shadow from the box and just use it as a shadow application.

2023-11-07 09:57 UTC, LucasFalkowsky commented on src/components/achievements/achievementCard/animatedShine.tsx
> +    const thresholdY = isMobile ? -35 : -70;
I think this should still be controlled by its parent component. The parent component should decide whether it is mobile or not.

2023-11-07 10:30 UTC, LucasFalkowsky commented on src/components/achievements/polaroid/completePolaroid.tsx
> +const CompletePolaroid: React.FC<CompletePolaroidProps> = ({ image, alternativeText, isMobile }) => {
This component is putting the image in the polaroid frame

2023-11-10 10:07 UTC, LomyW reviewed
Looks good to me! 😇 just minor changes

2023-11-10 10:08 UTC, LomyW commented on src/components/achievements/polaroid/completePolaroid.tsx
> +    alternativeText: string;
ignore this

2023-11-10 11:44 UTC, LucasFalkowsky commented on src/components/achievements/achievementCard/achievementCard.tsx
> +enum CardState {
Fixed in 978

2023-11-10 12:04 UTC, LomyW approved these changes
well done! 🥳

2023-11-10 12:04 UTC, LomyW approved these changes
well done! 🥳

2023-11-10 12:16 UTC, merged