feat: achievement modal
corona-school/user-app pull request #400
Opened 2023-11-06 10:45 UTC by LucasFalkowsky

closes https://github.com/corona-school/project-user/issues/978

Modal Components for Desktop and Mobile view were implemented.
Stories for Modal and Desktop Components were added.

2023-11-06 10:58 UTC, LucasFalkowsky commented on src/components/achievements/achievementCard/achievementCard.stories.mdx
> +import AchievementCard from './achievementCard';
This renaming was done, due to the changed purpose of this enum. It is used for everything achievement related now.

2023-11-06 10:59 UTC, LucasFalkowsky commented on src/components/achievements/cosmetics/newAchievementShine.tsx
> +        if (isLarge) {
if isLarge is passed as a prop we are scaling up the animation

2023-11-06 11:00 UTC, LucasFalkowsky commented on src/components/achievements/modals/achievementModal.tsx
> +                                    <Box position={'absolute'} top={'-40px'} left={'-40px'}>
due to a new scaling the position of this Animation was adjusted

2023-11-10 11:28 UTC, LomyW requested changes
All in all, beautiful components. We should just make sure that we maintain consistency and leave out the breakpoint for Tablet.

2023-11-10 11:28 UTC, LomyW commented on src/components/achievements/modals/achievementModal.tsx
> +    const isTablet = useBreakpointValue({ md: true, lg: false });
also here, no tablet breakpoint for consistency

2023-11-10 11:28 UTC, LomyW commented on src/components/achievements/modals/achievementModal.tsx
> +                width={isMobile || isTablet ? '100%' : '820px'}
also for better readability and consitency, we should create separate breakpoint values for the different props, like in the component `AppointmentCard.tsx`

2023-11-10 11:28 UTC, LomyW commented on src/components/achievements/modals/achievementModal.tsx
> +                                                    <Text color={Theme.colors.primary[500]} textAlign="center">
you could also user `color={"primary.500"}` here

2023-11-10 11:28 UTC, LomyW commented on src/components/achievements/progressIndicators/indicatorStep.tsx
> +    console.log(step, maxSteps, description, achievementState, isActive, isInactive);
remove log

2023-11-10 11:28 UTC, LomyW commented on src/components/achievements/progressIndicators/indicatorStep.tsx
> +                outlineWidth={isInactive ? '0' : '3px'}
does `outlineWidth` prop exist for VStacks? Get an error there

2023-11-10 11:28 UTC, LomyW commented on src/components/achievements/progressIndicators/indicatorStep.tsx
> +    console.log(step, maxSteps, description, achievementState, isActive, isInactive);
also here use `"primary.900"`, maybe direct in the text prop

2023-11-10 11:28 UTC, LomyW commented on src/components/achievements/progressIndicators/indicatorStep.tsx
> +                position={'absolute'}
also here for props you dont need a extra object `{}`

2023-11-10 11:28 UTC, LomyW commented on src/components/achievements/streak/StreakImage.tsx
> +                {/* <img width={'100%'} src={image} alt='' aria-hidden /> */}
why is this commented out?

2023-11-10 11:28 UTC, LomyW requested changes
All in all, beautiful components. We should just make sure that we maintain consistency and leave out the breakpoint for Tablet.

2023-11-10 11:56 UTC, LucasFalkowsky commented on src/components/achievements/helpers/achievement-image-helper.ts
> +import { PolaroidImageSize, PuzzleImageSize, ShineOffset, ShineSize } from '../types';
it should be in lower case ofc. Made that mistake for sure. Ill refactor this when we merged.

2023-11-10 11:57 UTC, LucasFalkowsky commented on src/components/achievements/achievementCard/achievementCard.tsx
> +                                width={isMobile ? '64px' : getPolaroidImageSize(isMobile, isMobile, true)}
the Component NewAchievementShine treats these states the same.

2023-11-10 12:14 UTC, LucasFalkowsky commented on src/components/achievements/progressIndicators/indicatorStep.tsx
> +                outlineWidth={isInactive ? '0' : '3px'}
it did work, even though it was underlined. But I fixed this by adding a border to the parent element.

2023-11-10 12:16 UTC, LucasFalkowsky commented on src/components/achievements/streak/StreakImage.tsx
> +                {/* <img width={'100%'} src={image} alt='' aria-hidden /> */}
for when it is decided, what to use. currently we have a dummy image in this component.

2023-11-10 14:10 UTC, LomyW commented on src/components/achievements/polaroid/completePolaroid.tsx
> +            height={`calc(${size} * 1.35)`}
for what is the calc and why do wie calc inline?

2023-11-10 14:12 UTC, LomyW commented on src/components/achievements/polaroid/completePolaroid.tsx
> +            top={size === PolaroidImageSize.SMALL ? 0 : getPolaroidOffset(size)}
why ternary? `getPolaroidOffset()` also checks small image size or?

2023-11-10 14:16 UTC, LomyW commented on src/components/achievements/modals/achievementModal.tsx
> +                                    <Text color={textColor} numberOfLines={7}>
soo we dont need `ellipsizeMode` here?

2023-11-10 14:18 UTC, LucasFalkowsky commented on src/components/achievements/polaroid/completePolaroid.tsx
> +            height={`calc(${size} * 1.35)`}
this calc is taking the width of the polaroid (the size value) and it gives the height a 1.35 aspect ratio to this width. This ensures, the polaroid always has the right aspect ratio, no matter the scaling.

2023-11-10 14:21 UTC, LucasFalkowsky commented on src/components/achievements/polaroid/completePolaroid.tsx
> +            top={size === PolaroidImageSize.SMALL ? 0 : getPolaroidOffset(size)}
true. I could just take the polaroidOffset return value. ' _ '*

2023-11-10 14:24 UTC, LomyW reviewed
nice work! ✨

2023-11-10 14:26 UTC, LucasFalkowsky commented on src/components/achievements/modals/achievementModal.tsx
> +                                    <Text color={textColor} numberOfLines={7}>
no. It makes the ... without the ellipsizeMode. Don't know why but it does.

2023-11-10 14:46 UTC, LomyW approved these changes

2023-11-10 14:49 UTC, merged