feat: implement progress page with dummy data
corona-school/user-app pull request #404
Opened 2023-11-10 11:42 UTC by LucasFalkowsky

closes https://github.com/corona-school/project-user/issues/977

implemented progress page

2023-11-14 11:21 UTC, LomyW commented on src/components/achievements/achievementCard/achievementCard.tsx
> +        <Link onPress={onClick}>
Why using Link and not `Pressable`

2023-11-14 11:35 UTC, LomyW commented on src/pages/Progress.tsx
> +import { Box, Divider, HStack, Stack, VStack, useBreakpointValue } from 'native-base';
We should rename it to AchievementProgress.tsx

2023-11-14 11:44 UTC, LucasFalkowsky commented on src/components/achievements/achievementCard/achievementCard.tsx
> +        <Link onPress={onClick}>
I did not know about this component. I changed the Link component in achievementCard and streakCard into the Pressable component

2023-11-14 14:46 UTC, LomyW requested changes
you make a good job!

2023-11-14 14:46 UTC, LomyW commented on src/pages/AchievementProgress.tsx
> +    // Sortieren von Beispiel Daten: Wird entfernt, wenn die Daten von der API kommen
please remove german comment

2023-11-14 14:47 UTC, LomyW reviewed
you make a good job! 
I would recommend to get rid of the size helpers and rather let the components handle it themselves (or implement a custom hook for it as commented)

2023-11-14 15:25 UTC, LucasFalkowsky commented on src/pages/Progress.tsx
> +            <VStack space={3}>
I made it react to the breakpoint value

2023-11-14 15:25 UTC, LucasFalkowsky commented on src/pages/AchievementProgress.tsx
> +                        <Stack marginTop={cardMargin}>
I already fixed this.

2023-11-14 15:27 UTC, LucasFalkowsky commented on src/components/achievements/progress-page-test-data.ts
> +        actionDescription: 'Ein Beispieltext für diesen Meilenstein...',
renamed every actionDescription

2023-11-14 15:29 UTC, LucasFalkowsky commented on src/pages/AchievementProgress.tsx
> +    const [collapsed, setCollapsed] = useState({
this collapsed is saving weather the streak container / completed / active / inactive container.

2023-11-14 15:34 UTC, LucasFalkowsky commented on src/pages/AchievementProgress.tsx
> +    }, [selectedAchievement, openModal]);
the value of the isNewAchievement variable is passed to the modal, when we open it. if a modal is not opened the value of selecteAchievement is undefined and openModal is false. if these values are not there, we can not set the isNewAchievement and we do not need it, since the modal is not open.
Then the values are given we have to check if the selectedAchievement is a streak or not, since streaks work different to other achievementTypes.  a streak just has a current step and max steps, when other achievements have the value newAchievement "isSeen" in db.

2023-11-14 15:35 UTC, LucasFalkowsky commented on src/components/achievements/cosmetics/InnerShadow.tsx
> +            <svg width="100%" height="100%" fill="none" xmlns="http://www.w3.org/2000/svg">
Hehe ThanQ

2023-11-14 15:38 UTC, LucasFalkowsky commented on src/components/achievements/AchievementImageContainer.tsx
> +    const breakpoint = useBreakpointValue({ base: breakpoints.base, md: breakpoints.md, lg: breakpoints.lg, xl: breakpoints.xl });
you are right, this is an overkill.

2023-11-14 15:40 UTC, LucasFalkowsky commented on src/pages/AchievementProgress.tsx
> +    achievements.forEach((achievement) => {
I think you mean a useMemo? useEffect would sort on each render.

2023-11-14 15:49 UTC, LucasFalkowsky commented on src/components/achievements/helpers/achievement-image-helper.ts
I would rather use a useCallback to memorize the functions. But since I would write the same code in every component that handles its own size, this would be very redundant.

2023-11-14 16:24 UTC, LucasFalkowsky commented on src/components/achievements/helpers/achievement-image-helper.ts
done!

2023-11-15 16:46 UTC, LomyW requested changes
nice work! some questions 🙂

2023-11-15 16:46 UTC, LomyW commented on src/components/achievements/achievementCard/achievementCard.tsx
> +    const indicatorSecond = useBreakpointValue({ base: true, md: false });
a question: we need this breakpoints only for tablet mode not for desktop?

2023-11-15 16:46 UTC, LomyW commented on src/components/achievements/AchievementImageContainer.tsx
> +            if (!image) return null;
do we only check here if a image exist? maybe we could check for the image before the switch?

2023-11-15 16:46 UTC, LomyW commented on src/components/achievements/modals/achievementModal.tsx
>                              <Button flex={1} variant="outline">
This button does the same as the close button and the close cross, right? So it actually closes the modal? 😃 maybe we should rethink that. In my opinion, this only makes sense if the maps are installed on other pages.

2023-11-15 16:46 UTC, LomyW commented on src/components/achievements/modals/achievementModal.tsx
>                              </Button>
here we will get a `actionRedirectLink`, could be external or internal.

2023-11-15 16:46 UTC, LomyW commented on src/components/achievements/modals/achievementModal.tsx
>                      {achievementState !== AchievementState.COMPLETED ? (
it also depends on the `achievementType`, to my knowledge only exists for sequential not for streak and tiered

2023-11-15 16:46 UTC, LomyW commented on src/components/achievements/polaroid/emptyPolaroidField.tsx
> +        <Box width={updatedSize} height={`calc(${updatedSize} * 1.35)`} position="relative">
here we use the same image two times, and lay them on top of each other? Can't this be one SVG?

2023-11-15 16:46 UTC, LomyW commented on src/components/achievements/streak/StreakImage.tsx
> +                <img width={'100%'} src={image} alt="" aria-hidden />
Can we use the `<Image />` from native base?

2023-11-15 16:46 UTC, LomyW commented on src/components/achievements/ProgressCollapsableHeadline.tsx
> +        }
here you can remove the disabling of eslint, is not bad if it is underlined

2023-11-15 16:46 UTC, LomyW commented on src/components/achievements/ProgressCollapsableHeadline.tsx
> +        <Link
the `<Link />` is there so that the whole line is clickable and not just the icon itself, right? Otherwise a `<IconButton />` could be used

2023-11-15 16:46 UTC, LomyW commented on src/components/achievements/achievementBadge.tsx
> +                right: `${!isInline && offsetRight}`,
can you try if a spread operator like `...!isInline && {top: '-15px', left: offsetLeft, right: offsetRight}` is possible?

2023-11-15 16:46 UTC, LomyW commented on src/components/achievements/progress-page-test-data.ts
> +        actionDescription: 'Ein Beispieltext für diesen Meilenstein...',
is this renamed?

2023-11-15 16:46 UTC, LomyW commented on src/components/achievements/types.ts
> +    buttonLabel?: string;
missing `isSeen`

2023-11-15 16:46 UTC, LomyW commented on src/widgets/AchievementProgress.tsx
> +    });
also here: we use the breakpoints only for tablet?

2023-11-15 16:48 UTC, LomyW commented on src/pages/AchievementProgress.tsx
> +            if (selectedAchievement.currentStep === selectedAchievement.maxSteps) {
no isSeen is a state (boolean) where we set if a user has already seen the new achievement

2023-11-16 07:20 UTC, LucasFalkowsky commented on src/components/achievements/achievementCard/achievementCard.tsx
> +    const indicatorSecond = useBreakpointValue({ base: true, md: false });
yes. They work the same. Achievement Cards also get displayed as cards on tablet.

2023-11-16 07:23 UTC, LucasFalkowsky commented on src/components/achievements/AchievementImageContainer.tsx
> +            if (!image) return null;
no we can't because we also have a case with AchievementType.TIERED, that does not require an image due to a fixed empty state.

2023-11-16 07:30 UTC, LucasFalkowsky commented on src/components/achievements/modals/achievementModal.tsx
>                              <Button flex={1} variant="outline">
well it is part of the design. Not my decision.

2023-11-16 07:38 UTC, LucasFalkowsky commented on src/components/achievements/modals/achievementModal.tsx
>                              </Button>
I repleced the button with Link and pass a button link variable

2023-11-16 07:40 UTC, LucasFalkowsky commented on src/components/achievements/polaroid/emptyPolaroidField.tsx
> +        <Box width={updatedSize} height={`calc(${updatedSize} * 1.35)`} position="relative">
no I decided to go this way, so the upper image casts the same shadow on the lower image as other elements are casting on the page. This is serving visual consistency. It used to be one image, but the shadows looked to diferent.

2023-11-16 07:40 UTC, LucasFalkowsky commented on src/components/achievements/streak/StreakImage.tsx
> +                <img width={'100%'} src={image} alt="" aria-hidden />
So right ^^

2023-11-16 08:34 UTC, LucasFalkowsky commented on src/components/achievements/ProgressCollapsableHeadline.tsx
> +        <Link
yes the whole line should be clickable. But just on mobile, so I gave the full width the clickable possibility. I also replaced it with Pressable.

2023-11-17 11:20 UTC, LomyW requested changes
really nice! ✨

2023-11-17 11:20 UTC, LomyW commented on src/components/achievements/modals/AchievementModal.tsx
> +                        {!steps && !maxSteps && progressDescription && (
so if we check for `!steps && !maxSteps` we cant pass the steps to an completed achievement or? wouldn't it be better if it were independent of the props nextstep and maxstep?

2023-11-17 11:20 UTC, LomyW commented on src/components/achievements/streak/streak-image-helper.ts
> +const getStreakImageSize = (size: StreakImageSize) => {
same question as last time? Can we remove the helper and handle it on the streak image container itself?

2023-11-17 11:20 UTC, LomyW commented on src/components/achievements/ProgressCollapsableHeadline.tsx
> +        >
I guess we have to `disable` the pressable on desktop. 
```suggestion
            disabled={!isCollapsable}
```

2023-11-17 11:22 UTC, LomyW commented on src/components/achievements/achievementCard/CardProgressDescription.tsx
> +        <HStack alignItems="flex-start" space="4px" justifyContent={justifyContent}>
<img width="258" alt="Bildschirmfoto 2023-11-17 um 11 51 34" src="https://github.com/corona-school/user-app/assets/115979086/2e0df871-a1ae-469e-9769-8bd972db28d5">

2023-11-17 11:26 UTC, LomyW commented on src/components/achievements/modals/AchievementModal.tsx
> +                            <VStack width={textBoxWidth} space={3} maxWidth={textBoxMaxWidth} height={textBoxHeight} alignItems={textBoxAlignItems}>
should this be at the same height? Maybe clearify with Johnny?
<img width="960" alt="Bildschirmfoto 2023-11-17 um 11 47 32" src="https://github.com/corona-school/user-app/assets/115979086/e34de570-bcc8-48e5-9944-01a7c67a8c41">

2023-11-17 12:21 UTC, LomyW commented on src/components/achievements/AchievementBadge.tsx
> +                </HStack>
<img width="108" alt="Bildschirmfoto 2023-11-17 um 12 06 31" src="https://github.com/corona-school/user-app/assets/115979086/c6bbddf6-8780-41b6-bb32-5853a7081180">

2023-11-17 14:44 UTC, LucasFalkowsky commented on src/components/achievements/progressIndicators/IndicatorBar.tsx
> +            <Text width={textWidth} textAlign={alignText} fontSize={centerText ? 'xs' : 'xs'} color="primary.500" height="fit-content" numberOfLines={1}>
should be 12 and 14 px so I changed it to that.

2023-11-17 14:53 UTC, LucasFalkowsky commented on src/components/achievements/achievementCard/CardProgressDescription.tsx
> +            <Text fontSize="xs" color={colorize ? 'primary.500' : 'black'} numberOfLines={numberOfLines}>
fixed

2023-11-17 14:53 UTC, LucasFalkowsky commented on src/components/achievements/achievementCard/AchievementCard.tsx
> +                                overflow="hidden"
it is used by default

2023-11-17 15:15 UTC, LucasFalkowsky commented on src/components/achievements/modals/AchievementModal.tsx
> +                            <VStack width={textBoxWidth} space={3} maxWidth={textBoxMaxWidth} height={textBoxHeight} alignItems={textBoxAlignItems}>
makes sense. I think we don't have to ask for that.

2023-11-17 15:31 UTC, LucasFalkowsky commented on src/components/achievements/achievementCard/CardProgressDescription.tsx
> +        <HStack alignItems="flex-start" space="4px" justifyContent={justifyContent}>
I just saw the height varies from desktop to mobile so now I made it adjust to the screen.

2023-11-17 15:45 UTC, LucasFalkowsky commented on src/components/achievements/modals/AchievementModal.tsx
> +                        {!steps && !maxSteps && progressDescription && (
I don't get it

2023-11-27 12:36 UTC, LomyW commented on src/pages/Progress.tsx
> +const achievements = gql(`
in this branch, the progress page is displayed purely with dummy data, right? So I would remove the query and create a new branch (also this is a extra ticket), in which we get real data from the database

2023-12-07 15:01 UTC, merged