Feat: next step cards
corona-school/user-app pull request #423
Opened 2023-12-15 14:15 UTC by LucasFalkowsky

What was done:

- addition of nextStepAchievements to ImportantInformation query
- change to NextStepCards
- addition of different modals for important information and next step achievements

still missing:

- icon discriminator for different important information types

<img src="https://media0.giphy.com/media/U23WekMlGy6cImpMim/giphy.gif"/>

2023-12-18 06:38 UTC, LomyW requested changes
some design changes 🎨

2023-12-18 07:22 UTC, LomyW requested changes
some changes 😇

2023-12-18 07:22 UTC, LomyW commented on src/helper/achievement-helper.ts
> +function convertDataToAchievement(dataWithType: AchievementsQueryType | InactiveAchievementsQueryType | NextStepAchievementsQueryType): Achievement[] {
maybe rename function to `convertAchievementToNextStep` and dataWithType to `achievementWithType`? Would specify it more to the usecase.

2023-12-18 07:22 UTC, LomyW commented on src/helper/achievement-helper.ts
>      type: 'achievements';
should type maybe a enum?

2023-12-18 07:22 UTC, LomyW commented on src/helper/achievement-helper.ts
> +function convertDataToAchievement(dataWithType: AchievementsQueryType | InactiveAchievementsQueryType | NextStepAchievementsQueryType): Achievement[] {
Is this something we cant handle in the resolver?

2023-12-18 07:22 UTC, LomyW commented on src/widgets/ImportantInformation.tsx
> +                                console.log('CLICKED!');
can you please remove the log here?

2023-12-18 07:22 UTC, LomyW commented on src/widgets/ImportantInformation.tsx
> +                        <NextStepsCard
for now we do not pass the `actionRedirectLink`` or?

2023-12-18 07:22 UTC, LomyW commented on src/widgets/ImportantInformation.tsx
> +                            actionDescription={t('moreInfoButton')}
Do we have a more precise description here?

2023-12-18 07:22 UTC, LomyW commented on src/widgets/ImportantInformation.tsx
> +                        <NextStepsCard
also here we dont pass the `actionRedirectLink`

2023-12-18 07:22 UTC, LomyW commented on src/components/achievements/nextStepsCard/NextStepsCard.tsx
> +            <Link width="288px" height="288px" href={actionRedirectLink}>
I think the link on the card itself should not be clickable, only the whole card.

2023-12-18 07:22 UTC, LomyW commented on src/components/achievements/nextStepsCard/NextStepsCard.tsx
> +                                <BooksIcon />
We should think about different Icons for the `ImportantInformations`

2023-12-18 08:39 UTC, LomyW requested changes
further idea 😁

2023-12-18 08:39 UTC, LomyW commented on src/widgets/ImportantInformation.tsx
> +                            name={`${t('important')}!`}
I think this is `info.title`. I guess the actual `title` (what is the subtitle) depends on the information type - which does not yet exist. But I think the type would make sense to a) get the icons and b) get the subtitles.

2023-12-18 10:46 UTC, LucasFalkowsky commented on src/helper/achievement-helper.ts
>  function checkAndGetSecondEnumValue<T extends Record<string, string>>(enumElement: any, comparator: T): keyof T | null {
This used to make sense when we had different enums in front and backend. But you are right. This function should be deleted by now. It was removed.

2023-12-18 10:51 UTC, LucasFalkowsky commented on src/helper/achievement-helper.ts
> +function convertDataToAchievement(dataWithType: AchievementsQueryType | InactiveAchievementsQueryType | NextStepAchievementsQueryType): Achievement[] {
This function is used on progress page and as next step so renaming would not make sense here. I renamed the incoming data. No this is resolving a typing issue that we have, when getting the data from the backend.

2023-12-18 12:23 UTC, LucasFalkowsky commented on src/helper/achievement-helper.ts
>      type: 'achievements';
Good objection!

2023-12-18 12:27 UTC, LucasFalkowsky commented on src/widgets/ImportantInformation.tsx
> +                        <NextStepsCard
Yes you are right I forgot to include it in the modal. the redirect link is used by the modal now, but still not the card, because that would be conflicting with the card being a modal opener.

2023-12-18 12:38 UTC, LucasFalkowsky commented on src/widgets/ImportantInformation.tsx
> +                            actionDescription={t('moreInfoButton')}
The more precise description would require an extra field in the database, if the usage is supposed to be easy. The button descriptions are used in the modal it self.
I added the possibility to write a description in the i18n file and if not, it takes moreInfoButton.

2023-12-18 12:40 UTC, LucasFalkowsky commented on src/widgets/ImportantInformation.tsx
> +                        <NextStepsCard
for the same reason. The redirect for this would be handled by the whole shabang above the return (the btnfn would redirect you in this case).

2023-12-18 12:43 UTC, LucasFalkowsky commented on src/components/achievements/nextStepsCard/NextStepsCard.tsx
> +            <Link width="288px" height="288px" href={actionRedirectLink}>
Thats what is happening here. We had a Pressable and if the onClick is undefined we would have used the Link.
I removed the Link anyway since the redirect would be handled by the parent component so this is not necessary here.

2023-12-19 07:36 UTC, LomyW reviewed
questions 😇

2023-12-20 14:25 UTC, LucasFalkowsky commented on src/helper/achievement-helper.ts
> +function convertDataToAchievement(dataWithType: AchievementsQueryType | InactiveAchievementsQueryType | NextStepAchievementsQueryType): Achievement[] {
the type graphql returns is not the type we pass in the resolver

2023-12-20 14:33 UTC, LucasFalkowsky commented on src/components/achievements/modals/NextStepModal.tsx
> +                        <Stack space={4} width="100%" direction={buttons?.length && buttons.length > 1 ? 'row' : 'column'} flexWrap="wrap">
the buttons being in a row works as long as there are just 2 buttons. 3 buttons would make the modal overflow in a lot of cases. But since we are talking about .length and not index, the number should be > 2 not >1 so this was fixed.

2023-12-20 14:35 UTC, LucasFalkowsky commented on src/helper/achievement-helper.ts
> +    achievements = 'achievements',
I originaly wanted to do that but when I tried to read FURTHERACHIEVEMENTS and NEXTSTEPACHIEVEMENTS I gave up on that idea. is this ok of a reason or you think I should change it?

2023-12-20 14:37 UTC, LucasFalkowsky commented on src/widgets/ImportantInformation.tsx
> +type Information = {
should we add it already or should we wait for a ticket that makes this necessary of a change.

2023-12-20 14:42 UTC, LucasFalkowsky commented on src/widgets/ImportantInformation.tsx
> +                        t(`helperwizard.${config.label}.actionDescription` as unknown as TemplateStringsArray, config.lang) || t('moreInfoButton');
nope because they did not exist prior to this update.

2023-12-20 14:46 UTC, LucasFalkowsky commented on src/widgets/ImportantInformation.tsx
> +                            actionDescription={t('moreInfoButton')}
I found that there is a i18n.exists function is used for such cases and implemented it with that.

2024-01-19 12:18 UTC, LomyW approved these changes
looks good to me 💯

2024-01-19 12:18 UTC, merged