Feat: achievements empty states
corona-school/user-app pull request #442
Opened 2024-01-15 09:35 UTC by LucasFalkowsky

closes https://github.com/corona-school/project-user/issues/1067

### What was done:

- empty state component was introduced

2024-01-19 12:43 UTC, LomyW commented on src/components/achievements/EmptyStateContainer.tsx
> +                    <Text fontWeight={600} fontSize="14px" lineHeight="17px" textAlign="center">
can we please use the pre-defined fontSizes like 'xs', 'sm' etc.?

2024-01-19 12:44 UTC, LomyW commented on src/components/achievements/EmptyStateContainer.tsx
> +                    <Text fontWeight={400} fontSize="10px" lineHeight="12px" textAlign="center">
also here? I think 10px is little bit too small

2024-01-19 12:52 UTC, LomyW requested changes
some notes ✨

2024-01-19 12:52 UTC, LomyW commented on src/components/achievements/EmptyStateContainer.tsx
> +                    <Text fontWeight={400} fontSize="10px" lineHeight="12px" textAlign="center">
also here, think 10px is little bit to small

2024-01-19 12:52 UTC, LomyW commented on src/components/achievements/EmptyStateContainer.tsx
> +                    </Text>
maybe something like that? (that it looks similar to the other empty states in the user app i.e. `AppointmentEmptyState``)
```suggestion
                     <Heading>{t('achievement.empty_state.Completed.title')}</Heading>
                    <Text maxW="700" textAlign="center" py="3">
                        {t('achievement.empty_state.Completed.description')}
                    </Text>
```

2024-01-19 12:52 UTC, LomyW commented on src/widgets/AchievementProgress.tsx
>                          <ProgressCollapsableHeadline achievementState={key} onClick={() => handleOnClick(undefined, key)} />
is the empty state also collapsable?

2024-01-19 14:13 UTC, LucasFalkowsky commented on src/components/achievements/EmptyStateContainer.tsx
> +                    <Text fontWeight={400} fontSize="10px" lineHeight="12px" textAlign="center">
It is exactly what the design sais. Thats why I used these values.
I changed them to the presets though.

2024-01-19 14:14 UTC, LucasFalkowsky commented on src/components/achievements/EmptyStateContainer.tsx
> +                    </Text>
But this is not as it was done in the design.

2024-01-22 12:44 UTC, LomyW approved these changes
Before merging please resolve the conflict.
Looks good to me. 🎉

2024-01-22 13:31 UTC, merged