Feat/lesson plan windows
corona-school/user-app pull request #738
Opened 2024-12-05 15:21 UTC by benjaminmay1

# Add AI-Powered Lesson Plan Generator

## Changes
- Added new Lesson Plan Generator page at `/lesson` route
- Added file upload capability for knowledge enhancement
- Implemented copy-to-clipboard functionality
- Added German translations for all lesson plan related text

## Features
- Generate lesson plans based on subject, grade level, duration, user prompt and files
- Support for file uploads (up to 3 files) to enhance AI context
- Interactive form with subject selection, grade level, and duration inputs
- Lesson plan generation with structured output
- Copy generated plan to clipboard
- Example lesson plan available for demo purposes
- Terms and conditions acceptance required for generation
- Responsive layout with two-column design

## Technical Details 
- Uses GraphQL mutation for lesson plan generation
- Integrates with existing navigation and authentication system
- Implements file upload via REST endpoint

## Screenshots
<img width="1154" alt="image" src="https://github.com/user-attachments/assets/ce798f5c-ecf2-4a1e-8797-b500b9069a58">

2024-12-20 08:32 UTC, JeangelLF requested changes
Thanks for the PR! I left some comments, let me know if you have any questions.

2024-12-20 08:32 UTC, JeangelLF commented on src/pages/Lesson.tsx
> +            console.log('Uploaded file UUIDs:', fileUuids);
Let's remove this one.

2025-02-03 13:12 UTC, MadeleineFrohnholzer commented on src/pages/Lesson.tsx
Vinay improved the mobile view: 
![image](https://github.com/user-attachments/assets/66858d4b-feb8-4b3e-b4d3-e4074a44671c)

And on Desktop it is better as well: 
![image](https://github.com/user-attachments/assets/737fe18f-cc5d-486e-9baf-5d1d1ff29bbf)

2025-02-28 09:08 UTC, JeangelLF approved these changes

2025-02-28 09:11 UTC, merged