Promote course button
corona-school/user-app pull request #84
Opened 2022-12-27 15:42 UTC by LomyW

Button for helpers, to promote a course again!
[Works with this [Backend](https://github.com/corona-school/backend/tree/feat/50-promote-course) ]

2022-12-28 15:16 UTC, jeffersondarcy commented on src/pages/SingleCourse.tsx
> +                        {subcourse && getTrafficStatus(subcourse!.participantsCount, subcourse!.maxParticipants) !== 'full' && (
maybe move this check to a function "shouldShowPromoteButton" or "isSubcourseNotFull" - same code is used in the next box

2022-12-28 15:21 UTC, jeffersondarcy commented on src/widgets/PromoteButton.tsx
> +        <div>
shouldn't this div be inside the condition and not rendered empty?

2022-12-29 09:00 UTC, timidak requested changes
Some changes to be made 🙂

2023-01-03 09:00 UTC, timidak commented on src/pages/SingleCourse.tsx
> +    const [promote, _promote] = useMutation(
You can just use destructuring here
```suggestion
    const [promote, { data, loading, error }] = useMutation(
```

2023-01-03 09:06 UTC, timidak requested changes
Two minor changes 😄

2023-01-03 09:06 UTC, timidak commented on src/pages/SingleCourse.tsx
> +            toast.show({ description: 'Kurs konnte nicht beworben werden' });
This should be moved to the translated strings

2023-01-03 09:06 UTC, timidak commented on src/widgets/PromoteButton.tsx
> +        if (!alreadyPromoted && capacity < 0.75 && isPublishedThreeDaysAgo(publishedAt)) {
I would wrap this in a function and just call it on the isDisabled prop on the button. 
Imho is no need for an effect here.

2023-01-03 10:24 UTC, timidak commented on src/widgets/PromoteButton.tsx
> +        }
hence the value in the if is a boolean you can just return it 😄 
To achieve the same behavior, you'll have to negate it.
```suggestion
        return !(!alreadyPromoted && capacity < 0.75 && isPublishedThreeDaysAgo(publishedAt)) 
```

2023-01-03 12:06 UTC, timidak approved these changes
LGTM 🎉

2023-01-03 13:29 UTC, jeffersondarcy commented on src/Utility.ts
> +    const status = participants >= maxParticipants ? 'full' : maxParticipants - participants <= 5 ? 'last' : 'free';
could be done without variable like the previous version

2023-01-03 13:32 UTC, jeffersondarcy commented on src/pages/SingleCourse.tsx
> +                            <PromoteButton
I think it would be better to check the conditions before rendering the button and just tell the button if it should be enabled or disabled

2023-01-03 14:45 UTC, jeffersondarcy commented on src/widgets/PromoteButton.tsx
> +const PromoteButton: React.FC<Props> = ({ isDisabled, loading, promote }) => {
do you need to pass loading, or can you apply isDisabled logic before

2023-01-03 14:46 UTC, jeffersondarcy commented on src/widgets/PromoteButton.tsx
> +const PromoteButton: React.FC<Props> = ({ isDisabled, loading, promote }) => {
I would rename promote to something generic like onClick

2023-01-03 14:48 UTC, jeffersondarcy commented on src/pages/SingleCourse.tsx
> +    const cannotPromoteCourse = () => {
why don't you check subcourse, subcourse.published and loading here? than you would only have one piece of logic

2023-01-03 14:50 UTC, LomyW commented on src/pages/SingleCourse.tsx
> +    const cannotPromoteCourse = () => {
thought of not displaying the button if the subcourse isn't published - not only disable the button.

2023-01-03 15:01 UTC, jeffersondarcy commented on src/pages/SingleCourse.tsx
> +        if (!subcourse) return;
maybe !subcourse || subcourse.published should still return false, just in case it is not checked in render?

2023-01-03 15:01 UTC, jeffersondarcy approved these changes

2023-01-03 15:09 UTC, jeffersondarcy approved these changes

2023-01-03 15:10 UTC, merged