Appointment tile in storybook
corona-school/user-app pull request #91
Opened 2023-01-04 15:22 UTC by LomyW

Appointment tile is added to storybook!

2023-01-04 15:33 UTC, jeffersondarcy approved these changes

2023-01-04 15:44 UTC, timidak requested changes
Looks pretty good 👍🏼 Just a few changes in wording to be made imho.

2023-01-04 15:44 UTC, timidak commented on src/helper/appointment-helper.ts
> +const getCourseDate = (courseStart: string, duration: number) => {
Please type what the function is returning.

2023-01-04 15:44 UTC, timidak commented on src/helper/appointment-helper.ts
> +type courseDate = {
types should begin with a capital letter

2023-01-04 15:44 UTC, timidak commented on src/helper/appointment-helper.ts
> +const getCourseDate = (courseStart: string, duration: number) => {
The naming seems to be off. 
I would either change the name to what it's really doing or split this function into `isCourseTakingPlaceRightNow` and `getCourseTimeText`

2023-01-04 15:44 UTC, timidak commented on src/helper/appointment-helper.ts
> +        currentOrNot: false,
isCurrentlyTakingPlace? Otherwise I don't really now if its current Or Not? 😄

2023-01-04 15:44 UTC, timidak commented on src/helper/appointment-helper.ts
> +const getCourseDay = (courseDate: string) => {
Would type the return value again

2023-01-04 15:44 UTC, timidak commented on src/widgets/appointment/AppointmentTile.tsx
> +                    {/* BUG: have to be: {t("appointment.tile.videoButton")}  */}
What is buggy here?

2023-01-04 15:44 UTC, timidak commented on src/widgets/appointment/AppointmentTile.tsx
> +            <Card bg={current ? 'primary.900' : 'primary.100'} shadow={'none'}>
```suggestion
            <Card bg={current ? 'primary.900' : 'primary.100'} shadow="none">
```

2023-01-04 15:44 UTC, timidak commented on src/widgets/appointment/AppointmentTile.tsx
> +const AppointmentTile: React.FC<Props> = ({ timeText, courseTitle, courseInstructor, current }) => {
timeDescriptionText maybe? and isCurrentlyTakingPlace?

2023-01-04 15:44 UTC, timidak commented on src/widgets/appointment/AppointmentDate.tsx
> +                <Text fontSize={'md'} bold>
`"xs"` and `"md"` can be passed without an object.

2023-01-09 11:05 UTC, timidak commented on src/helper/appointment-helper.ts
> +    }
We should add this to i18next

2023-01-16 11:00 UTC, timidak reviewed
Some minor changes ☺️

2023-01-16 11:00 UTC, timidak commented on src/helper/appointment-helper.ts
> +    }
`return start <= now && now < end;` add this instead of line 20 to 28 and it should do the job. ☺️

2023-01-16 11:00 UTC, timidak commented on src/helper/appointment-helper.ts
> +    }
This should be enough, too. I guess ☺️ 
```suggestion
    if (start <= now && now < end) {
        return i18n.t('appointment.clock.nowToEnd', { end: endTime });
    } 
    return i18n.t('appointment.clock.startToEnd', { start: startTime, end: endTime });
```

2023-01-17 14:34 UTC, merged