Appointment details component
corona-school/user-app pull request #94
Opened 2023-01-16 10:56 UTC by LomyW

Component for appointment details.
In storybook are **three versions** of the details surface.
To navigate to the page in the user-app, follow: [http://localhost:3000/single-appointment/1](http://localhost:3000/single-appointment/1)

2023-01-16 13:10 UTC, jeffersondarcy commented on src/components/appointment/AppointmentDetail.tsx
> +    userType?: string;
shouldn't userType be something like enum?

2023-01-16 13:11 UTC, jeffersondarcy commented on src/components/appointment/AppointmentDetail.tsx
> +            {/* Avatare  */}
```suggestion
            {/* Avatars  */}
```

2023-01-16 13:21 UTC, jeffersondarcy commented on src/helper/appointment-helper.ts
> +const isCourseTakingPlaceRightNow = (courseStart: string, duration: number): boolean => {
the name is a bit misleading, because the function does not take a course as parameter. would it make sense to use course as parameter or do you get the start and duration from somewhere else?
How about a shorter name, like isCourseNow or isLectureNow?

2023-01-16 13:23 UTC, jeffersondarcy commented on src/helper/appointment-helper.ts
> +type CourseTimes = {
I don't think now belongs here

2023-01-16 13:28 UTC, jeffersondarcy commented on src/helper/appointment-helper.ts
> +    const { start, end, now } = getCourseTimes(courseStart, duration);
I think you might not need the getCourseTimes function and just calculate values here or do you re-use it somewhere? For me there are to many functions with confusing names doing similar calculations

2023-01-23 13:57 UTC, jeffersondarcy commented on src/components/appointment/AppointmentDetail.tsx
> +type AppointmentDetailProps = {
I think it might be better to pass an Object instead of individual props

2023-01-23 14:04 UTC, jeffersondarcy commented on src/pages/appointment/SingleAppointment.tsx
> +const SingleAppointment = () => {
If you are keeping this component, why not rename it in just 'Appointment'?

2023-01-23 14:05 UTC, jeffersondarcy commented on src/components/appointment/AppointmentDetail.tsx
> +                        appointmentType === 'GROUP' ? 'appointment.appointmentDetail.group' : 'appointment.appointmentDetail.oneToOne',
should there be an appointment types enum?

2023-01-23 14:13 UTC, jeffersondarcy commented on src/NavigatorLazy.tsx
> +                path="/single-appointment/:id"
would just 'appointment' be a better url?

2023-01-23 14:47 UTC, jeffersondarcy commented on src/pages/appointment/SingleAppointment.tsx
> +const SingleAppointment = () => {
I would rename this component to "Appointment" and move it to the parent folder pages

2023-01-23 14:50 UTC, jeffersondarcy commented on src/pages/appointment/SingleAppointment.tsx
> +                id={1}
will the data come from a hook in future? I would put the test data in an object and change the component to receive an object instead of individual props

2023-01-23 15:23 UTC, jeffersondarcy commented on src/components/appointment/AppointmentDetail.tsx
> +            <Button width={buttonWidth} isDisabled={appointment.meetingLink ? false : true} onPress={() => window.open(appointment.meetingLink, '_blank')}>
there is no restriction on how early the link can be clicked, right?

2023-01-23 15:27 UTC, jeffersondarcy commented on src/components/appointment/AppointmentDetail.tsx
> +                        appointment.appointmentType === 'GROUP' ? 'appointment.appointmentDetail.group' : 'appointment.appointmentDetail.oneToOne',
you are not using AppointmentTypes yet :)

2023-01-23 15:29 UTC, jeffersondarcy requested changes
looks good, just some minor changes needed

2023-01-24 07:36 UTC, LomyW commented on src/NavigatorLazy.tsx
> +                path="/single-appointment/:id"
I would pass the appointment id with the parameter.

2023-01-24 07:46 UTC, LomyW commented on src/components/appointment/AppointmentDetail.tsx
> +            <Button width={buttonWidth} isDisabled={appointment.meetingLink ? false : true} onPress={() => window.open(appointment.meetingLink, '_blank')}>
not yet.

2023-01-24 15:45 UTC, jeffersondarcy commented on src/components/appointment/AppointmentDetail.tsx
> +                        ?.map((i) => <Avatar>{<StudentAvatar style={{ margin: '-1' }} />}</Avatar>)
names are not rendered, is it correct?

2023-01-24 16:12 UTC, jeffersondarcy commented on src/widgets/appointment/AppointmentTile.tsx
> +    onPressToAppointment: () => void;
maybe just "onPress" ?

2023-01-24 16:13 UTC, jeffersondarcy approved these changes
some minor improvements suggested

2023-01-24 16:24 UTC, LomyW commented on src/components/appointment/AppointmentDetail.tsx
> +                        ?.map((i) => <Avatar>{<StudentAvatar style={{ margin: '-1' }} />}</Avatar>)
not in the avatars, only in the header

2023-01-27 15:07 UTC, jeffersondarcy approved these changes

2023-01-30 10:34 UTC, jeffersondarcy approved these changes

2023-01-30 10:35 UTC, merged