Feat/64 appointment list
corona-school/user-app pull request #97
Opened 2023-01-18 14:50 UTC by LomyW

todo: some mini stylings and - maybe - renaming 😄

2023-01-18 15:23 UTC, jeffersondarcy commented on src/NavigatorLazy.tsx
> +                        <SwitchUserType pupilComponent={<Appointments />} studentComponent={<Appointments />} />
do we need this switch?

2023-01-18 15:35 UTC, jeffersondarcy commented on src/helper/appointment-helper.ts
> +        console.log(DateTime.fromISO(appointment.startDate) > now);
log should be removed

2023-01-18 15:37 UTC, jeffersondarcy commented on src/helper/appointment-helper.ts
> +        console.log('current ' + currentId);
do you want to keep this logs?

2023-01-18 15:49 UTC, jeffersondarcy commented on src/widgets/appointment/Appointment.tsx
>          setIsCurrent(isCourseTakingPlaceRightNow(courseStart, duration));
I am not sure about this logic. Does isCurrent need to be in state - it is only changing with changing props and not by a user-interaction

2023-01-18 15:53 UTC, jeffersondarcy commented on src/widgets/appointment/Appointment.tsx
>      useEffect(() => {
I don't think useEffect is needed here

2023-01-18 15:55 UTC, jeffersondarcy commented on src/widgets/appointment/Appointment.tsx
>      const [isCurrent, setIsCurrent] = useState<boolean>(false);
```suggestion
    const isCurrent = isCourseTakingPlaceRightNow(courseStart, duration));
```

2023-01-18 15:55 UTC, jeffersondarcy commented on src/widgets/appointment/Appointment.tsx
>      const [isCurrent, setIsCurrent] = useState<boolean>(false);
can we do it without state?

2023-01-18 15:58 UTC, jeffersondarcy requested changes
please check if state and useEffect are required in Appointment.tsx

2023-01-19 08:17 UTC, timidak approved these changes
👍🏼 LGTM

2023-01-19 08:21 UTC, merged